defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:6.11.5
    - image: circleci/node:8.8.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm i
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm t
          command: npm t
      - run:
          name: lint
          command: npm run lint

workflows:
  version: 2
  ci-cd:
    jobs:
      - build
      - test:
          requires:
            - build
